cd few-shot-video-classification/ && CUDA_VISIBLE_DEVICES=0 python finetune_metatrain.py --video_path /home/linhanxi/home_data/k400_CMNsplit/ \
--train_list_path data/kinetics100/data_splits/meta_train_filtered.txt \
--val_video_path /home/linhanxi/home_data/k400_CMNsplit/ \
--val_list_path data/kinetics100/data_splits/trainclasses_val_filtered.list \
--dataset kinetics \
--n_classes 400 \
--n_finetune_classes 64 \
--model CLIP_RN50 \
--model_depth 34 \
--batch_size 32 \
--n_threads 4 \
--checkpoint 1 \
--val_every 1 \
--train_crop random \
--n_samples_for_each_video 8 \
--n_val_samples 10 \
--weight_decay 0.001 \
--layer_lr 0.001 0.001 0.001 0.001 0.001 0.1 \
--ft_begin_index 0 \
--result_path /media/sda1/linhanxi/exp/few-shot-vid-cls/finetune_kinetics_CLIP_RN50_freezeBasemodel \
--emb_dim 1024 --sample_size 224 --print_freq 1 --sample_duration 16 --is_amp #--clip_duration 2
# --pretrain_path /home/linhanxi/nfs_mount/30902_hdd_sda1_linhanxi/pretrained_weights/few-shot-video-classification/fsv_pretrained_model/r25d34_sports1m.pth \