CUDA_VISIBLE_DEVICES=0 python finetune_metatrain.py --video_path /media/hdd/sda1/linhanxi/data/ss_v2/extracted_frms_OTAM/ssv2_256x256q5/train/ \
--train_list_path data//somethingv2/data_splits/meta_train.txt \
--val_video_path /media/hdd/sda1/linhanxi/data/ss_v2/extracted_frms_OTAM/ssv2_256x256q5/val/ \
--val_list_path data//somethingv2/data_splits/meta_train_val.txt \
--dataset something \
--n_classes 400 \
--n_finetune_classes 64 \
--pretrain_path /media/hdd/sda1/linhanxi/pretrained_weights/few-shot-video-classification/fsv_pretrained_model/r25d34_sports1m.pth \
--model r2plus1d \
--model_depth 34 \
--batch_size 32 \
--n_threads 16 \
--checkpoint 1 \
--val_every 1 \
--train_crop random \
--n_samples_for_each_video 8 \
--n_val_samples 10 \
--weight_decay 0.001 \
--layer_lr 0.001 0.001 0.001 0.001 0.001 0.1 \
--ft_begin_index 0 \
--result_path /media/hdd/sda1/linhanxi/exp/few-shot-vid-cls/finetune_something
# /home/linhanxi/home_data/ssv2_extracted_frms_OTAM/