cd few-shot-video-classification/ &&  CUDA_VISIBLE_DEVICES=1 python finetune_metatrain.py --video_path /home/linhanxi/diving48_240p/frames_240p/ \
--train_list_path data/diving48V2/meta_train.txt \
--val_video_path /home/linhanxi/diving48_240p/frames_240p/ \
--val_list_path data/diving48V2/meta_trainval.txt \
--dataset diving48V2 \
--n_classes 400 \
--n_finetune_classes 36 \
--pretrain_path /home/linhanxi/nfs_mount/30902_hdd_sda1_linhanxi/pretrained_weights/few-shot-video-classification/fsv_pretrained_model/r25d34_sports1m.pth \
--model r2plus1d \
--model_depth 34 \
--batch_size 32 \
--n_threads 4 \
--checkpoint 1 \
--val_every 1 \
--train_crop random \
--n_samples_for_each_video 8 \
--n_val_samples 10 \
--weight_decay 0.001 \
--layer_lr 0.001 0.001 0.001 0.001 0.001 0.1 \
--ft_begin_index 0 \
--result_path /media/sda1/linhanxi/exp/few-shot-vid-cls/finetune_diving48V2/TSL/debug_resume \
--resume_path /media/sda1/linhanxi/exp/few-shot-vid-cls/finetune_diving48V2/TSL/debug/save_20.pth \
--is_amp
# /home/linhanxi/home_data/ssv2_extracted_frms_OTAM/