cd few-shot-video-classification/ && CUDA_VISIBLE_DEVICES=0 python tsl_fsv.py --test_video_path /home/linhanxi/home_data/k400_CMNsplit/ \
--manual_seed 10 \
--test_list_path data/kinetics100/data_splits/meta_test_filtered.txt \
--dataset kinetics100 \
--n_classes 64 \
--train_crop random \
--n_samples_for_each_video 10 \
--n_val_samples 10 \
--clip_model r2plus1d \
--clip_model_depth 34 \
--n_threads 4 \
--result_path /media/sda1/linhanxi/exp/few-shot-vid-cls/test_kinetics_save_2_10way1shot_metaTest_run2 \
--shot 1 \
--test_way 10 \
--query 5 \
--resume_path /media/sda1/linhanxi/exp/few-shot-vid-cls/finetune_kinetics/save_2.pth \
--emb_dim 512 \
--batch_size 64 \
--lr 0.01 \
--nepoch 10 \
--is_amp